# Generated by Django 5.1.1 on 2025-03-30 18:08

from django.db import migrations


from django.db import migrations

def create_tag_categories(apps, schema_editor):

    from plants.utils.tag_constants import TAG_EMOJIS
    
    PlantTagCategory = apps.get_model('plants', 'PlantTagCategory')
    PlantTag = apps.get_model('plants', 'PlantTag')
    
    for tag_data in TAG_EMOJIS:
        # Create the category
        category, created = PlantTagCategory.objects.get_or_create(
            name=tag_data['name'],
            defaults={
                'emoji': tag_data['emoji'],
                'color': tag_data['color']
            }
        )
        
        # Create the tag with the same name as the category
        tag, created = PlantTag.objects.get_or_create(
            name=tag_data['name'],
            defaults={
                'category': category
            }
        )

def delete_tag_categories(apps, schema_editor):
    # For reversing the migration if needed
    PlantTagCategory = apps.get_model('plants', 'PlantTagCategory')
    PlantTag = apps.get_model('plants', 'PlantTag')
    
    for tag_data in apps.get_model('plants', 'utils.tag_constants').TAG_EMOJIS:
        PlantTag.objects.filter(name=tag_data['name']).delete()
        PlantTagCategory.objects.filter(name=tag_data['name']).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tag_categories),
    ]
